name: takeoff-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - opencv
  - matplotlib
  - pillow
  - "numpy<2"
  - pip
  - pip:
      - albumentations
      - segmentation-models-pytorch
      - pytesseract
